from starlette.config import Config

config = Config(".env")

# DATABASE
DATABASE_CREDENTIALS = config("DATABASE_CREDENTIALS")
_DATABASE_CREDENTIAL_USER, _DATABASE_CREDENTIAL_PASSWORD = str(DATABASE_CREDENTIALS).split(":")
DATABASE_CLUSTER_NAME = config("DATABASE_CLUSTER_NAME")
DATABASE_CLUSTER_ID = config("DATABASE_CLUSTER_ID")
DATABASE_NAME = config("DATABASE_NAME")
MONGO_DATABASE_URI = f"mongodb+srv://{_DATABASE_CREDENTIAL_USER}:{_DATABASE_CREDENTIAL_PASSWORD}@{DATABASE_CLUSTER_NAME}.{DATABASE_CLUSTER_ID}.mongodb.net/?retryWrites=true&w=majority&appName={DATABASE_CLUSTER_NAME}"
